toolbar:
  - undo redo | styleselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist outdent indent | removeformat 
  - image | link | charmap | code | fullscreen | help

plugins:
  - image
  - link
  - insertdatetime lists media table code help wordcount
  - fullscreen
